name: floating_dots
description: Creates a group of floating dots (or a single floating dot) that travel at a random speed from one edge of the screen to another.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter